version: "3"
services:
  backend:
    image: "backend"
    build:
      context: .
    volumes:
      - .:/go/src/app
    env_file:
      - env_vars.env
    depends_on:
      - db

  db:
    image: arm64v8/mongo
    volumes:
      - /srv/docker/Niete/mongodb/data/db:/data/db
      - /srv/docker/Niete/mongodb/data/configdb:/data/configdb